version: "3"
services:
  webserver:
    container_name: node-app
    image: node
    build: node
    volumes:
      - ./node/app:/app
    tty: true
    ports:
     - 8080:3000
    networks:
      - mynet
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    networks:
      - mynet

networks:
  mynet:
    driver: bridge